### ISSUE TITLE
About fine-tuned detector

### ISSUE THREAD

**Issue by hoyeYang** [fredzzhang/spatio-attentive-graphs#27]
Hi, I wonder after fine-tuning the object detector on HICO-DET, whether you retrain your hoi classification model or just replace the object detector at the test time.

**Comment by fredzzhang** [comment]
Hi, @hoyeYang 

As shown in the table of performance on the front page, all results correspond to a single model, which we trained using a pre-trained object detector. So to answer your question, we did not re-train our model after fine-tuning the detector. This is out of concerns for fair comparison, since other works that used fine-tuned detectors also did not re-train their models (or at least we think so).

Let me know if you have other questions.

Cheers,
Fred

**Comment by hoyeYang** [comment]
Thanks a lot. I'll close this issue.
